name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.6.1
author: yohom <382146139@qq.com>
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.16
  rxdart:  ^0.22.2
  intl: ^0.16.0
  kiwi: ^0.2.0
  encrypt: ^3.3.1
  crypto: ^2.1.1
  flutter_advanced_networkimage: ^0.5.0
  connectivity: ^0.4.3+7
  flushbar: ^1.8.2
  oktoast: ^2.2.0

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter