name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.12.13
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  rxdart:  ^0.24.1
  kiwi: ^0.2.0
  flutter_localizations:
    sdk: flutter
  encrypt: ^4.0.0
  crypto: ^2.1.3
  flutter_advanced_networkimage: ^0.7.0
  oktoast: ^2.3.2
  flutter_svg: ^0.17.4

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter