name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.9.1
author: yohom <382146139@qq.com>
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.7
  rxdart:  ^0.23.1
  kiwi: ^0.2.0
  flutter_localizations:
    sdk: flutter
  encrypt: ^3.3.1
  crypto: ^2.1.3
  flutter_advanced_networkimage: ^0.6.2
  flushbar: ^1.9.1
  oktoast: ^2.2.1

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter