name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.3.2
author: yohom <382146139@qq.com>
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.6
  rxdart:  ^0.22.0
  intl: ^0.15.8
  kiwi: ^0.1.0
  encrypt: ^2.0.0
  crypto: ^2.0.6
  flutter_advanced_networkimage: ^0.5.0-alpha.3
  flutter_svg: ^0.13.0+1
  connectivity: ^0.4.2+2
#  flushbar: ^1.5.3
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar
      ref: dev_version

dev_dependencies:
  mockito: 4.0.0
  flutter_test:
    sdk: flutter